version: "3.7"

services:
  juridico-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: juridico-front
    restart: always
    ports:
      - "8081:80"
    networks:
      - juridico-network
