# version: "3.7"

# services:
#   juridico-front:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: juridico-front
#     restart: always
#     ports:
#       - "8082:80"
#     networks:
#       - juridico_api_juridico-network
#     # volumes:
#     #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#     #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
# networks:
#   juridico_api_juridico-network:
#     external: false
# for local development
version: '3.7'
services:
  juridico-front:
    build:
      context: .
    container_name: juridico-front
    ports:
      - "${PORTDOCKER}:8080"
      - 443:443
    restart: always
    volumes:
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
